ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ com.guardiangrow.app.ApplicationKt.module ]
  }
}

app {
  jwt {
    issuer = "guardiangrow"
    audience = "guardiangrow-web"
    realm = "guardiangrow"
    accessTokenTtlSeconds = 900
  }
}

db {
  enabled = true
  jdbcUrl = "jdbc:oracle:thin:@//MAK:1521/XEPDB1"
  username = "guardian"
  password = "guardian"
}
